spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      binders:
        myMessage:
          group: order
server:
  port: 8763
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
    instance-id: http://192.168.140.78:8763 #服务中心的信息显示（如果IP地址不显示的话，进行配置）
  client:
    service-url:
      defaultZone: http://192.168.140.78:8760/eureka/,http://192.168.140.78:8761/eureka/
